---

# mastera kubectl yüklenecek.
- name: install kubectl
  yum:
    name: kubectl
    state: present
    allow_downgrade: yes

#
- name: initialize K8S cluster
  shell: kubeadm init --pod-network-cidr=172.16.0.0/16

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes

- name: install Pod network
  become: yes
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: create .kube directory
  file:
    path: /home/ansadmin/.kube
    state: directory
    mode: 0755
- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansadmin/.kube/config
    remote_src: yes