---
- name: Add Jetstack chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Create cert-manager namespace
  shell: kubectl create namespace cert-manager

- name: Deploy cert-manager chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    chart_version: 1.5.1
    update_repo_cache: True
  